/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SellerProfile, Transaction } from './types';

export const SEED_SELLERS: SellerProfile[] = [
  {
    id: 's-1',
    name: 'Amara Couture',
    handle: '@amara_couture',
    phone: '+234 803 111 2222',
    category: 'Fashion & Apparel',
    trustScore: 98,
    successfulSales: 142,
    activeEscrows: 3,
    disputeCount: 0,
    responseTime: '5 mins',
    rating: 4.9,
  },
  {
    id: 's-2',
    name: 'Gadget Hub Lagos',
    handle: '@gadgethub_lagos',
    phone: '+234 812 345 6789',
    category: 'Electronics & Gadgets',
    trustScore: 94,
    successfulSales: 310,
    activeEscrows: 5,
    disputeCount: 2,
    responseTime: '12 mins',
    rating: 4.6,
  },
  {
    id: 's-3',
    name: 'Thrift Wonders',
    handle: '@thrift_wonders_ng',
    phone: '+234 905 555 4433',
    category: 'Lifestyle & Thrift',
    trustScore: 87,
    successfulSales: 64,
    activeEscrows: 1,
    disputeCount: 3,
    responseTime: '25 mins',
    rating: 4.2,
  },
  {
    id: 's-4',
    name: 'Prestige Kicks',
    handle: '@prestige_kicks',
    phone: '+234 708 999 8877',
    category: 'Footwear & Luxury',
    trustScore: 99,
    successfulSales: 215,
    activeEscrows: 2,
    disputeCount: 1,
    responseTime: '3 mins',
    rating: 4.9,
  },
];

export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: 'VP-10924',
    productName: 'Ovation High-Top Sneakers (White/Coral)',
    category: 'Footwear & Luxury',
    amount: 45000,
    sellerId: 's-4',
    sellerName: 'Prestige Kicks',
    sellerHandle: '@prestige_kicks',
    sellerPhone: '+234 708 999 8877',
    buyerName: 'Femi Adebayo',
    buyerPhone: '+234 802 888 7766',
    deliveryPartner: 'GIG Logistics',
    trackingNumber: 'GIG-7492-930',
    deliveryTimelineDays: 3,
    terms: 'Must be size 43, original box, and tags intact. Deliver to Lekki Phase 1.',
    status: 'COMPLETED',
    createdAt: '2026-06-29T10:30:00Z',
    timeline: [
      {
        id: 't1-1',
        status: 'DRAFT',
        title: 'Agreement Created',
        description: 'Femi Adebayo created an escrow agreement with Prestige Kicks.',
        timestamp: '2026-06-29T10:30:00Z',
        actor: 'BUYER',
      },
      {
        id: 't1-2',
        status: 'PAYMENT_SECURED',
        title: 'Payment Deposited into Escrow',
        description: 'OPay secured NGN 45,000 in VeriPay Escrow. Seller notified.',
        timestamp: '2026-06-29T11:15:00Z',
        actor: 'SYSTEM',
      },
      {
        id: 't1-3',
        status: 'DISPATCHED',
        title: 'Shipped via GIG Logistics',
        description: 'Seller dispatched package. Tracking #GIG-7492-930 created.',
        timestamp: '2026-06-30T09:00:00Z',
        actor: 'SELLER',
      },
      {
        id: 't1-4',
        status: 'DELIVERED',
        title: 'Package Delivered',
        description: 'GIG Logistics courier delivered package. Buyer confirmed receipt.',
        timestamp: '2026-07-01T14:20:00Z',
        actor: 'LOGISTICS',
      },
      {
        id: 't1-5',
        status: 'COMPLETED',
        title: 'Funds Released to Seller',
        description: 'Buyer confirmed successful delivery. NGN 45,000 released to Prestige Kicks wallet.',
        timestamp: '2026-07-01T14:45:00Z',
        actor: 'BUYER',
      },
    ],
  },
  {
    id: 'VP-11048',
    productName: 'Refurbished iPad Air 2022 (64GB, Space Gray)',
    category: 'Electronics & Gadgets',
    amount: 280000,
    sellerId: 's-2',
    sellerName: 'Gadget Hub Lagos',
    sellerHandle: '@gadgethub_lagos',
    sellerPhone: '+234 812 345 6789',
    buyerName: 'Femi Adebayo',
    buyerPhone: '+234 802 888 7766',
    deliveryPartner: 'DHL Express',
    trackingNumber: 'DHL-8392-104',
    deliveryTimelineDays: 2,
    terms: 'No scratches on screen, battery health > 85%, charger included. 48hr testing window.',
    status: 'DISPUTED',
    createdAt: '2026-06-30T14:15:00Z',
    dispute: {
      id: 'disp-11048',
      openedBy: 'BUYER',
      reason: 'Wrong Product / Damaged Item',
      description: 'The iPad arrived with a deep vertical scratch across the screen. The seller claimed it was pristine. I refuse to accept this unless we do a partial refund or full return.',
      buyerEvidence: [
        { id: 'ev-1', type: 'image', name: 'scratch_screen.jpg', url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&auto=format&fit=crop' },
        { id: 'ev-2', type: 'image', name: 'unboxing_photo.jpg', url: 'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=500&auto=format&fit=crop' },
      ],
      sellerEvidence: [
        { id: 'ev-3', type: 'image', name: 'shipping_package_ready.jpg', url: 'https://images.unsplash.com/photo-1612115539055-fa8ef2c44247?w=500&auto=format&fit=crop' },
      ],
      buyerMessage: 'I would like a return or NGN 40,000 partial refund to replace the screen glass.',
      sellerMessage: 'The device was perfectly clean when packed. It must have been damaged in transit or the buyer caused it after opening.',
      arbitrationStatus: 'UNDER_REVIEW',
      verdictDescription: 'OPay Arbitration Team is reviewing the DHL logistics insurance and the unboxing photo provided by the buyer.',
      createdAt: '2026-07-02T10:00:00Z',
    },
    timeline: [
      {
        id: 't2-1',
        status: 'DRAFT',
        title: 'Agreement Created',
        description: 'Femi Adebayo created an escrow agreement with Gadget Hub Lagos.',
        timestamp: '2026-06-30T14:15:00Z',
        actor: 'BUYER',
      },
      {
        id: 't2-2',
        status: 'PAYMENT_SECURED',
        title: 'Payment Secured in Escrow',
        description: 'OPay secured NGN 280,000 in VeriPay Escrow. Seller preparing shipment.',
        timestamp: '2026-06-30T15:00:00Z',
        actor: 'SYSTEM',
      },
      {
        id: 't2-3',
        status: 'DISPATCHED',
        title: 'Shipped via DHL Express',
        description: 'Seller dispatched iPad. Tracking #DHL-8392-104.',
        timestamp: '2026-07-01T10:30:00Z',
        actor: 'SELLER',
      },
      {
        id: 't2-4',
        status: 'DELIVERED',
        title: 'Delivered to Buyer',
        description: 'DHL Courier confirmed delivery. Femi Adebayo received package.',
        timestamp: '2026-07-02T09:15:00Z',
        actor: 'LOGISTICS',
      },
      {
        id: 't2-5',
        status: 'DISPUTED',
        title: 'Dispute Filed by Buyer',
        description: 'Femi Adebayo filed a dispute: Deep vertical scratch on screen.',
        timestamp: '2026-07-02T10:00:00Z',
        actor: 'BUYER',
      },
    ],
  },
  {
    id: 'VP-11239',
    productName: 'Custom Ankara Ballgown & Headtie',
    category: 'Fashion & Apparel',
    amount: 65000,
    sellerId: 's-1',
    sellerName: 'Amara Couture',
    sellerHandle: '@amara_couture',
    sellerPhone: '+234 803 111 2222',
    buyerName: 'Femi Adebayo',
    buyerPhone: '+234 802 888 7766',
    deliveryPartner: 'Fez Delivery',
    trackingNumber: 'FEZ-4820-192',
    deliveryTimelineDays: 4,
    terms: 'Custom measurements provided. Matching purple headtie must be included. Ship by Thursday.',
    status: 'IN_TRANSIT',
    createdAt: '2026-07-01T08:00:00Z',
    timeline: [
      {
        id: 't3-1',
        status: 'DRAFT',
        title: 'Agreement Created',
        description: 'Femi Adebayo created an escrow agreement with Amara Couture.',
        timestamp: '2026-07-01T08:00:00Z',
        actor: 'BUYER',
      },
      {
        id: 't3-2',
        status: 'PAYMENT_SECURED',
        title: 'Payment Secured',
        description: 'OPay secured NGN 65,000 in VeriPay Escrow. Amara Couture initiated fitting/tailoring check.',
        timestamp: '2026-07-01T09:12:00Z',
        actor: 'SYSTEM',
      },
      {
        id: 't3-3',
        status: 'DISPATCHED',
        title: 'Dispatched via Fez Delivery',
        description: 'Amara Couture shipped gown. Transit package is active.',
        timestamp: '2026-07-02T16:40:00Z',
        actor: 'SELLER',
      },
    ],
  },
  {
    id: 'VP-11352',
    productName: 'Premium Vintage Retro Oversized Shirts (Bundle of 3)',
    category: 'Lifestyle & Thrift',
    amount: 18500,
    sellerId: 's-3',
    sellerName: 'Thrift Wonders',
    sellerHandle: '@thrift_wonders_ng',
    sellerPhone: '+234 905 555 4433',
    buyerName: 'Femi Adebayo',
    buyerPhone: '+234 802 888 7766',
    deliveryPartner: 'Gokada Express',
    trackingNumber: '',
    deliveryTimelineDays: 1,
    terms: 'One silk floral pattern, two solid linen (white & olive green). Size L.',
    status: 'PENDING_PAYMENT',
    createdAt: '2026-07-03T09:00:00Z',
    timeline: [
      {
        id: 't4-1',
        status: 'DRAFT',
        title: 'Agreement Initialized',
        description: 'Escrow agreement initialized by buyer. Awaiting payment to secure funds.',
        timestamp: '2026-07-03T09:00:00Z',
        actor: 'BUYER',
      },
    ],
  },
];
